import type { Metadata } from "next";
import { Syne, Outfit } from "next/font/google";
import Script from "next/script";
import CookieConsent from "@/components/CookieConsent";
import "./globals.css";

const syne = Syne({
  variable: "--font-syne",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const SITE_URL = "https://trilo.dev";
const GA_MEASUREMENT_ID = "G-RJBVRJNB2V";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: "Trilo — Decide, Compare, Build. Continuously.",
    template: "%s | Trilo",
  },
  description:
    "Trilo is a state-aware product development system that continuously guides builders in deciding, comparing, and executing how their product is built — while preserving clarity at every step. Memory-backed architecture decisions, trade-off comparisons, and execution tracking — connected to your IDE via MCP.",
  keywords: [
    // ── Core identity ──
    "state-aware development system",
    "continuous product guidance",
    "AI decision system for builders",
    "persistent solution architect",
    "product development guidance system",
    "decision loop with memory",
    "AI architecture advisor",
    // ── Decision & comparison ──
    "tech stack comparison tool",
    "build vs buy analysis",
    "architecture trade-off comparison",
    "decision tracking software",
    "software architecture decisions",
    "AI-powered decision support",
    "compare development approaches",
    "technology evaluation tool",
    // ── Memory & state ──
    "stateful AI planning",
    "context-aware development tool",
    "RAG-powered development assistant",
    "decision memory system",
    "architecture decision record",
    "structured state management",
    // ── Execution & tracking ──
    "development execution tracking",
    "architecture to execution pipeline",
    "task breakdown from decisions",
    "development milestone tracking",
    "planning and execution connected",
    // ── MCP / Integrations ──
    "MCP integration",
    "Model Context Protocol",
    "Cursor AI integration",
    "VS Code AI planning",
    "Replit integration",
    "Lovable integration",
    "Bolt.new integration",
    "Windsurf integration",
    // ── Audience ──
    "tools for startup CTOs",
    "founder development tools",
    "product manager tech planning",
    "solo developer architecture",
    "engineering team planning software",
    // ── Long-tail / semantic ──
    "how to make better architecture decisions",
    "AI that remembers your tech decisions",
    "continuous software planning tool",
    "guided product development AI",
    "what should I build next AI",
    "reduce uncertainty in software development",
    "clarity in product development",
    "Trilo development system",
    "trilo.dev",
  ],
  applicationName: "Trilo",
  authors: [{ name: "Trilo", url: SITE_URL }],
  creator: "Trilo",
  publisher: "Trilo",
  generator: "Next.js",
  referrer: "origin-when-cross-origin",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: false,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  icons: {
    icon: [
      { url: "/favicon-32x32.png", sizes: "32x32", type: "image/png" },
      { url: "/favicon-16x16.png", sizes: "16x16", type: "image/png" },
    ],
    apple: [
      { url: "/apple-touch-icon.png", sizes: "180x180", type: "image/png" },
    ],
    other: [
      { rel: "mask-icon", url: "/trilo-logo.png", color: "#00e8a2" },
    ],
  },
  alternates: {
    canonical: SITE_URL,
  },
  openGraph: {
    title: "Trilo — Decide, Compare, Build. Continuously.",
    description:
      "A state-aware system that continuously guides builders in deciding, comparing, and executing how their product is built. Memory-backed decisions, trade-off analysis, and execution tracking — connected to your IDE via MCP.",
    type: "website",
    siteName: "Trilo",
    url: SITE_URL,
    locale: "en_US",
    // OG image auto-generated by app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: "Trilo — Decide, Compare, Build. Continuously.",
    description:
      "A state-aware product development system. Memory-backed architecture decisions, trade-off comparisons, and execution tracking — connected to Cursor, VS Code, and more via MCP.",
    creator: "@trilodev",
    site: "@trilodev",
    // Twitter image auto-generated by app/twitter-image.tsx
  },
  category: "Technology",
  classification: "Software Development Tools",
  other: {
    // ── Browser & platform meta ──
    "theme-color": "#00e8a2",
    "color-scheme": "dark",
    "msapplication-TileColor": "#030305",
    "msapplication-config": "none",
    "apple-mobile-web-app-capable": "yes",
    "apple-mobile-web-app-status-bar-style": "black-translucent",
    "apple-mobile-web-app-title": "Trilo",
    "mobile-web-app-capable": "yes",
    // ── Search engine verification (replace with real tokens) ──
    "google-site-verification": "EAddZXY0jJxMAQBW1vEoJj2EZ9YM6b3jJtcUSi3j2U0",
    // "msvalidate.01": "YOUR_BING_VERIFICATION_TOKEN",
    // "yandex-verification": "YOUR_YANDEX_VERIFICATION_TOKEN",
    // ── Pinterest / Slack ──
    "og:email": "hello@trilo.dev",
    "slack-app-id": "",
  },
};

/* ── JSON-LD Structured Data ─────────────────────────────────── */

const organizationSchema = {
  "@context": "https://schema.org",
  "@type": "Organization",
  name: "Trilo",
  url: SITE_URL,
  logo: `${SITE_URL}/trilo-logo.png`,
  description:
    "Trilo builds a state-aware product development system that continuously guides builders through architecture decisions, trade-off comparisons, and execution — while preserving clarity at every step.",
  sameAs: [
    "https://twitter.com/trilodev",
    "https://github.com/trilodev",
  ],
  foundingDate: "2025",
};

const softwareSchema = {
  "@context": "https://schema.org",
  "@type": "SoftwareApplication",
  name: "Trilo",
  description:
    "A state-aware product development system that continuously guides builders in deciding, comparing, and executing how their product is built. Memory-backed decisions, structured comparisons, execution tracking, and MCP integration with your IDE.",
  url: SITE_URL,
  applicationCategory: "DeveloperApplication",
  operatingSystem: "Web",
  offers: {
    "@type": "Offer",
    price: "0",
    priceCurrency: "USD",
    availability: "https://schema.org/PreOrder",
    description: "Join the waitlist — launching 2026",
  },
  featureList: [
    "State-aware intelligence — remembers every architecture decision, constraint, and trade-off",
    "Continuous guidance — ask 'what should I do next?' and get contextual answers",
    "Compare & simulation engine — evaluate approaches by time, cost, and complexity before committing",
    "Decision ownership — recommendations you can accept, reject, or override",
    "Trilo Board — execution tracking with tasks and milestones linked to decisions",
    "MCP integration — guidance appears inside Cursor, VS Code, and other build tools",
    "Structured state + semantic memory (RAG) — not chat history, real decision records",
  ],
  creator: {
    "@type": "Organization",
    name: "Trilo",
  },
};

const webPageSchema = {
  "@context": "https://schema.org",
  "@type": "WebPage",
  name: "Trilo — Decide, Compare, Build. Continuously.",
  description:
    "A state-aware product development system that guides builders through every decision — from architecture to execution — with memory, comparison, and continuous clarity.",
  url: SITE_URL,
  isPartOf: {
    "@type": "WebSite",
    name: "Trilo",
    url: SITE_URL,
  },
  about: {
    "@type": "Thing",
    name: "Product Development Decision System",
  },
  significantLink: `${SITE_URL}/#waitlist`,
};

const faqSchema = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: [
    {
      "@type": "Question",
      name: "What is Trilo?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Trilo is a state-aware product development system that continuously guides builders in deciding, comparing, and executing how their product is built. It remembers every architecture decision, constraint, and trade-off — then uses that context to guide what should happen next. It is not a one-time planner or a passive assistant. It is a continuous system that stays with your product.",
      },
    },
    {
      "@type": "Question",
      name: "How does Trilo use MCP (Model Context Protocol)?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Trilo connects with development tools like Cursor, VS Code, Replit, Lovable, and others via the Model Context Protocol (MCP). This means Trilo's guidance appears inside your development workflow — not as a separate tool you switch to, but as a system you work with. Your decisions, comparisons, and execution context travel with you into your IDE.",
      },
    },
    {
      "@type": "Question",
      name: "Who is Trilo for?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Trilo is built for founders, product managers, solo developers, startup CTOs, and engineering teams who need continuous clarity throughout product development. If you've ever lost track of why a decision was made, underestimated complexity, or didn't know what to build next — Trilo is built for you.",
      },
    },
    {
      "@type": "Question",
      name: "When will Trilo launch?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Trilo is launching in 2026. You can join the waitlist now to get early access and be among the first to experience continuous product development guidance.",
      },
    },
    {
      "@type": "Question",
      name: "What development platforms does Trilo integrate with?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Trilo integrates with build platforms and development tools via MCP, including Cursor, Lovable, Bolt.new, VS Code, Replit, Windsurf, GitHub, Vercel, Supabase, Linear, Notion, Figma, and Builder.io. The goal is for Trilo to exist inside the builder's workflow, not outside it.",
      },
    },
    {
      "@type": "Question",
      name: "Is Trilo free?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Trilo will offer a free tier when it launches. A premium tier called FastTrack will provide deeper execution support, structured task breakdowns, and advanced comparison features. Join the waitlist for early access and exclusive pricing.",
      },
    },
    {
      "@type": "Question",
      name: "How is Trilo different from ChatGPT or other AI tools?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "ChatGPT and similar tools are stateless — every conversation starts from scratch. Trilo maintains structured state and semantic memory (RAG) across your entire product lifecycle. It remembers your decisions, understands your constraints, and provides guidance based on what has already been decided — not generic suggestions. AI in Trilo powers explanation and interaction, but decisions are stored as structured records, not chat history.",
      },
    },
    {
      "@type": "Question",
      name: "What is the Trilo Board?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "The Trilo Board is the execution and tracking layer where tasks, milestones, and progress are tracked. Unlike a generic project board, every task on the Trilo Board is linked to the architecture decision that created it — so planning and execution are never separate. What you decided is always connected to what you're building.",
      },
    },
    {
      "@type": "Question",
      name: "How does Trilo remember my decisions?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Trilo uses a structured state layer combined with semantic memory (RAG). Architecture decisions, tech stack choices, feature scope, constraints, and progress are stored explicitly — not as chat logs. Conversations are retrievable, and all future guidance is contextual to what has already been decided. The system never resets.",
      },
    },
  ],
};

const videoSchema = {
  "@context": "https://schema.org",
  "@type": "VideoObject",
  name: "Trilo — The Lifecycle Protocol",
  description:
    "See how Trilo continuously guides product development — from architecture decisions to trade-off comparisons to execution tracking. A state-aware system that remembers every decision and guides what should happen next.",
  thumbnailUrl: `${SITE_URL}/api/video-thumbnail`,
  uploadDate: "2026-03-13T00:00:00Z",
  contentUrl: `${SITE_URL}/Trilo__Idea_to_Execution.mp4`,
  embedUrl: `${SITE_URL}/#demo`,
  duration: "PT2M",
  isFamilyFriendly: true,
  inLanguage: "en",
  requiresSubscription: false,
  publisher: {
    "@type": "Organization",
    name: "Trilo",
    logo: {
      "@type": "ImageObject",
      url: `${SITE_URL}/trilo-logo.png`,
      width: 1024,
      height: 1024,
    },
  },
  potentialAction: {
    "@type": "WatchAction",
    target: `${SITE_URL}/#demo`,
  },
};

const breadcrumbSchema = {
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  itemListElement: [
    {
      "@type": "ListItem",
      position: 1,
      name: "Home",
      item: SITE_URL,
    },
    {
      "@type": "ListItem",
      position: 2,
      name: "Waitlist",
      item: `${SITE_URL}/#waitlist`,
    },
  ],
};

const webSiteSchema = {
  "@context": "https://schema.org",
  "@type": "WebSite",
  name: "Trilo",
  url: SITE_URL,
  description:
    "A state-aware product development system. Continuously guide decisions, compare trade-offs, and track execution — with memory that never resets.",
  publisher: {
    "@type": "Organization",
    name: "Trilo",
  },
  potentialAction: {
    "@type": "SearchAction",
    target: `${SITE_URL}/?q={search_term_string}`,
    "query-input": "required name=search_term_string",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="ltr" className="dark" suppressHydrationWarning>
      <head>
        {/* ── JSON-LD Structured Data ── */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(organizationSchema),
          }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(softwareSchema),
          }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(webPageSchema),
          }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(faqSchema),
          }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(videoSchema),
          }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(breadcrumbSchema),
          }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(webSiteSchema),
          }}
        />
      </head>
      <body
        className={`${syne.variable} ${outfit.variable} antialiased`}
      >
        {children}
        <CookieConsent />

        {/* ── Google Analytics with Consent Mode ── */}
        <Script id="ga-consent-defaults" strategy="beforeInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('consent', 'default', {
              analytics_storage: 'denied',
              wait_for_update: 500
            });
          `}
        </Script>
        <Script
          src={`https://www.googletagmanager.com/gtag/js?id=${GA_MEASUREMENT_ID}`}
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', '${GA_MEASUREMENT_ID}');
          `}
        </Script>
      </body>
    </html>
  );
}
