import type { Metadata } from "next";
import { Syne, Outfit } from "next/font/google";
import Script from "next/script";
import CookieConsent from "@/components/CookieConsent";
import "./globals.css";

const syne = Syne({
  variable: "--font-syne",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const SITE_URL = "https://trilo.dev";
const GA_MEASUREMENT_ID = "G-RJBVRJNB2V";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: "Trilo — From Idea to Architecture in Minutes | AI Software Planning",
    template: "%s | Trilo",
  },
  description:
    "Turn your product idea into a complete engineering blueprint. Get AI-powered technology stack recommendations, system architecture design, realistic timelines, and cost estimates — then send your plan to Cursor, Replit, or Lovable via MCP to start building.",
  keywords: [
    // ── Primary product terms ──
    "software architecture planner",
    "AI development planning",
    "tech stack recommendation tool",
    "solution architect AI",
    "system design tool",
    "project estimation software",
    "software blueprint generator",
    "development cost estimator",
    "architecture decision tool",
    // ── MCP / Integrations ──
    "MCP integration",
    "Model Context Protocol",
    "Cursor AI integration",
    "Replit integration",
    "Lovable integration",
    "Bolt.new integration",
    "VS Code AI planning",
    "Windsurf integration",
    // ── Use-case keywords ──
    "AI project planning",
    "software development planner",
    "startup tech stack",
    "engineering blueprint",
    "build vs buy analysis",
    "development timeline estimator",
    "software architecture automation",
    "AI solution architect",
    "automated system design",
    "project scope estimator",
    // ── Audience keywords ──
    "tools for startup CTOs",
    "founder development tools",
    "product manager tech planning",
    "solo developer architecture",
    "engineering team planning software",
    // ── Long-tail / semantic ──
    "how to plan software architecture",
    "AI that designs software systems",
    "generate tech stack from idea",
    "software planning tool 2026",
    "idea to code pipeline",
    "blueprint to code workflow",
    "architecture as a service",
    "pre-development planning AI",
    "Trilo software planner",
    "trilo.dev",
  ],
  applicationName: "Trilo",
  authors: [{ name: "Trilo", url: SITE_URL }],
  creator: "Trilo",
  publisher: "Trilo",
  generator: "Next.js",
  referrer: "origin-when-cross-origin",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: false,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  icons: {
    icon: [
      { url: "/favicon-32x32.png", sizes: "32x32", type: "image/png" },
      { url: "/favicon-16x16.png", sizes: "16x16", type: "image/png" },
    ],
    apple: [
      { url: "/apple-touch-icon.png", sizes: "180x180", type: "image/png" },
    ],
    other: [
      { rel: "mask-icon", url: "/trilo-logo.png", color: "#00e8a2" },
    ],
  },
  alternates: {
    canonical: SITE_URL,
  },
  openGraph: {
    title: "Trilo — From Idea to Architecture in Minutes",
    description:
      "Describe what you want to build. Get a complete engineering blueprint — stack, architecture, timeline, and cost. Then send it to your favorite build platform via MCP.",
    type: "website",
    siteName: "Trilo",
    url: SITE_URL,
    locale: "en_US",
    // OG image auto-generated by app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: "Trilo — From Idea to Architecture in Minutes",
    description:
      "Describe what you want to build. Get a complete engineering blueprint — then send it to Cursor, Replit, or Lovable via MCP.",
    creator: "@trilodev",
    site: "@trilodev",
    // Twitter image auto-generated by app/twitter-image.tsx
  },
  category: "Technology",
  classification: "Software Development Tools",
  other: {
    // ── Browser & platform meta ──
    "theme-color": "#00e8a2",
    "color-scheme": "dark",
    "msapplication-TileColor": "#030305",
    "msapplication-config": "none",
    "apple-mobile-web-app-capable": "yes",
    "apple-mobile-web-app-status-bar-style": "black-translucent",
    "apple-mobile-web-app-title": "Trilo",
    "mobile-web-app-capable": "yes",
    // ── Search engine verification (replace with real tokens) ──
    "google-site-verification": "EAddZXY0jJxMAQBW1vEoJj2EZ9YM6b3jJtcUSi3j2U0",
    // "msvalidate.01": "YOUR_BING_VERIFICATION_TOKEN",
    // "yandex-verification": "YOUR_YANDEX_VERIFICATION_TOKEN",
    // ── Pinterest / Slack ──
    "og:email": "hello@trilo.dev",
    "slack-app-id": "",
  },
};

/* ── JSON-LD Structured Data ─────────────────────────────────── */

const organizationSchema = {
  "@context": "https://schema.org",
  "@type": "Organization",
  name: "Trilo",
  url: SITE_URL,
  logo: `${SITE_URL}/trilo-logo.png`,
  description:
    "AI-powered software architecture and development planning platform.",
  sameAs: [
    "https://twitter.com/trilodev",
    "https://github.com/trilodev",
  ],
  foundingDate: "2025",
};

const softwareSchema = {
  "@context": "https://schema.org",
  "@type": "SoftwareApplication",
  name: "Trilo",
  description:
    "Turn your product idea into a complete engineering blueprint with AI-powered architecture planning, tech stack recommendations, timelines, and cost estimates.",
  url: SITE_URL,
  applicationCategory: "DeveloperApplication",
  operatingSystem: "Web",
  offers: {
    "@type": "Offer",
    price: "0",
    priceCurrency: "USD",
    availability: "https://schema.org/PreOrder",
    description: "Join the waitlist — launching 2026",
  },
  featureList: [
    "AI-powered tech stack recommendations",
    "System architecture design",
    "Development timeline estimation",
    "Cost estimation",
    "Scenario comparison (build vs buy)",
    "Execution roadmap generation",
    "MCP integration with Cursor, Replit, Lovable, and more",
  ],
  creator: {
    "@type": "Organization",
    name: "Trilo",
  },
};

const webPageSchema = {
  "@context": "https://schema.org",
  "@type": "WebPage",
  name: "Trilo — From Idea to Architecture in Minutes",
  description:
    "Turn your product idea into a complete engineering blueprint. AI-powered software architecture planning with MCP integrations.",
  url: SITE_URL,
  isPartOf: {
    "@type": "WebSite",
    name: "Trilo",
    url: SITE_URL,
  },
  about: {
    "@type": "Thing",
    name: "Software Architecture Planning",
  },
  significantLink: `${SITE_URL}/#waitlist`,
};

const faqSchema = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: [
    {
      "@type": "Question",
      name: "What is Trilo?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Trilo is an AI-powered software architecture and development planning platform. You describe what you want to build, and Trilo generates a complete engineering blueprint including technology stack recommendations, system architecture design, development timelines, and cost estimates.",
      },
    },
    {
      "@type": "Question",
      name: "How does Trilo use MCP (Model Context Protocol)?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Trilo creates your engineering blueprint, then sends it directly to your favorite build platform — like Cursor, Replit, Lovable, Bolt.new, or VS Code — via the Model Context Protocol (MCP). This means you go from idea to code-ready plan to actual building in one seamless workflow.",
      },
    },
    {
      "@type": "Question",
      name: "Who is Trilo for?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Trilo is built for founders, product managers, solo developers, startup CTOs, and engineering teams who want to make informed architecture decisions before writing code. It eliminates guesswork from technology selection, timeline estimation, and cost planning.",
      },
    },
    {
      "@type": "Question",
      name: "When will Trilo launch?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Trilo is launching in 2026. You can join the waitlist now to get early access and be among the first to plan smarter.",
      },
    },
    {
      "@type": "Question",
      name: "What development platforms does Trilo integrate with?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Trilo integrates with a wide range of build platforms via MCP, including Cursor, Lovable, Bolt.new, VS Code, Replit, Windsurf, GitHub, Vercel, Supabase, Linear, Notion, Figma, and Builder.io.",
      },
    },
    {
      "@type": "Question",
      name: "Is Trilo free?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Trilo will offer a free tier when it launches. Join the waitlist to be among the first to get early access and exclusive pricing.",
      },
    },
    {
      "@type": "Question",
      name: "How is Trilo different from ChatGPT or other AI tools?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Unlike general AI chatbots, Trilo is purpose-built for software architecture planning. It generates structured, actionable engineering blueprints with technology stack recommendations, system architecture diagrams, development timelines, cost breakdowns, and build-vs-buy analyses — then sends them directly to your IDE or build platform via MCP.",
      },
    },
  ],
};

const videoSchema = {
  "@context": "https://schema.org",
  "@type": "VideoObject",
  name: "Trilo — From Idea to Execution",
  description:
    "Watch how Trilo transforms your product idea into a complete engineering blueprint with AI-powered architecture planning, tech stack recommendations, timelines, and cost estimates.",
  thumbnailUrl: `${SITE_URL}/api/video-thumbnail`,
  uploadDate: "2026-03-13T00:00:00Z",
  contentUrl: `${SITE_URL}/Trilo__Idea_to_Execution.mp4`,
  embedUrl: `${SITE_URL}/#demo`,
  duration: "PT2M",
  isFamilyFriendly: true,
  inLanguage: "en",
  requiresSubscription: false,
  publisher: {
    "@type": "Organization",
    name: "Trilo",
    logo: {
      "@type": "ImageObject",
      url: `${SITE_URL}/trilo-logo.png`,
      width: 1024,
      height: 1024,
    },
  },
  potentialAction: {
    "@type": "WatchAction",
    target: `${SITE_URL}/#demo`,
  },
};

const breadcrumbSchema = {
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  itemListElement: [
    {
      "@type": "ListItem",
      position: 1,
      name: "Home",
      item: SITE_URL,
    },
    {
      "@type": "ListItem",
      position: 2,
      name: "Waitlist",
      item: `${SITE_URL}/#waitlist`,
    },
  ],
};

const webSiteSchema = {
  "@context": "https://schema.org",
  "@type": "WebSite",
  name: "Trilo",
  url: SITE_URL,
  description:
    "AI-powered software architecture and development planning platform. From idea to blueprint in minutes.",
  publisher: {
    "@type": "Organization",
    name: "Trilo",
  },
  potentialAction: {
    "@type": "SearchAction",
    target: `${SITE_URL}/?q={search_term_string}`,
    "query-input": "required name=search_term_string",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="ltr" className="dark" suppressHydrationWarning>
      <head>
        {/* ── JSON-LD Structured Data ── */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(organizationSchema),
          }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(softwareSchema),
          }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(webPageSchema),
          }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(faqSchema),
          }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(videoSchema),
          }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(breadcrumbSchema),
          }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(webSiteSchema),
          }}
        />
      </head>
      <body
        className={`${syne.variable} ${outfit.variable} antialiased`}
      >
        {children}
        <CookieConsent />

        {/* ── Google Analytics with Consent Mode ── */}
        <Script id="ga-consent-defaults" strategy="beforeInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('consent', 'default', {
              analytics_storage: 'denied',
              wait_for_update: 500
            });
          `}
        </Script>
        <Script
          src={`https://www.googletagmanager.com/gtag/js?id=${GA_MEASUREMENT_ID}`}
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', '${GA_MEASUREMENT_ID}');
          `}
        </Script>
      </body>
    </html>
  );
}
